apiVersion: v1
kind: Service
metadata:
  name: document-api
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 3000
  selector:
    app: document-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-api
  template:
    metadata:
      labels:
        app: document-api
    spec:
      containers:
        - name: document-api
          image: '#{DockerSrouceImage}#'
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: ENV
              value: '#{ENV}#'
            - name: DB_HOST
              value: '#{DB_HOST}#'
            - name: DB_PASSWORD
              value: '#{DB_PASSWORD}#'
            - name: DB_PORT
              value: '#{DB_PORT}#'
            - name: DB_USER
              value: '#{DB_USER}#'
            - name: DB_DATABASE
              value: '#{DB_NAME}#'
            - name: DEBUG
              value: '#{DEBUG}#'
